dist: bionic
language: python
jobs:
  include:
    - services: docker
    - os: osx
      language: shell
    - os: windows
      language: shell
env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to a PyPI API token in Travis settings
python:
  - 3.7
  - 3.8
  - 3.9-dev
install:
  - pip install -U setuptools pip wheel
  - pip install -e .[dev]
script:
  - pytest tests.py
after_success:
  - |
    if [[ $TRAVIS_TAG ]]; then
      python3 -m pip install twine
      ./setup.py sdist bdist_wheel
      python3 -m twine upload dist/*.whl
    fi
